# Use the appropriate ASP.NET Core runtime as the base image
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80    

# Use the appropriate .NET SDK image to build the app
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["CompanyProfile.csproj", "./"]
RUN dotnet restore "CompanyProfile.csproj"
COPY . .
WORKDIR "/src/"
RUN dotnet build "CompanyProfile.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "CompanyProfile.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "CompanyProfile.dll"]
