# Use the appropriate ASP.NET Core runtime as the base image
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80

# Use the appropriate .NET SDK image to build the app
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["ApplyForJob.csproj", "./"]
#COPY ../SahredContent .
RUN dotnet restore "ApplyForJob.csproj"
COPY . .
WORKDIR "/src/"
RUN dotnet build "ApplyForJob.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ApplyForJob.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ApplyForJob.dll"]
